### ISSUE TITLE
Texture glitch on cube demo

### ISSUE THREAD

**Issue by Veltas** [breakintoprogram/lib-spectrum#2]
![image](https://user-images.githubusercontent.com/2104118/79119491-644ccb00-7d88-11ea-887a-e01c2627dc06.png)

Have noticed possible glitch drawing the texture on the cube demo, see left of the bottom face of cube. A few pixels from the background picture appear where the base's texture should be. Not sure if actual bug or just caused by timing of the routine that copies the rendered frame over.

Screenshot taken of fuse-gtk.

**Comment by breakintoprogram** [comment]
That was me being lazy for the sake of a handful of T-states per line. I've fixed that in the latest version of vector_filled.z80, which has just been dropped in. Thanks for the contribution.
