### ISSUE TITLE
Scroll Demo with Attributes

### ISSUE THREAD

**Issue by robpearmain** [breakintoprogram/lib-spectrum#3]
The scroll demo does not include an example of using attributes.

The scroll code is just awesome work, thanks so much, it has reignited my interest in z80 assembler for the Spectrum after a hiatus of 11 years since I developed Bipboi

**Comment by breakintoprogram** [comment]
Hi Rob, thanks for the encouragement. I've dropped a new version of the scroller demo on. Please note that I've noticed a couple of issues with it whilst merging the changes from another piece of code:

1. The colours don't seem to work if the scroll goes faster than 1 pixel per frame.
2. The sprites seem to get a bit more flickery as the scrolling progresses.

Not had chance to iron out those issues, but this should be enough to demonstrate the principle.

**Comment by robpearmain** [comment]
Thanks Dean

I will check it out and then send you a demo of what I have been working on

Best regards

Rob

**Comment by robpearmain** [comment]
Hi Dean

Interesting, I got around the colour issues by Putting a blank row of tiles
between each change of colour and checking to see if the current map
position was not on 0 or 8 (and 7) and if so draw a row of attribute
colours at the top or bottom of each row, (2 rows if on 0 or 8, 3 if not)
but this was slow and went over the 25FPS boundary

Using bright yellows or greens and bright white blank tiles minimises the
Attribute clash effect

Best regards

Rob
